BEGIN;

CREATE TABLE consent_records (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id UUID REFERENCES users(id) ON DELETE SET NULL, lead_id UUID REFERENCES leads(id) ON DELETE SET NULL, document_version_id UUID NOT NULL REFERENCES legal_document_versions(id) ON DELETE RESTRICT, action VARCHAR(10) NOT NULL CHECK(action IN ('GRANTED','REVOKED')), channel VARCHAR(30) NOT NULL, ip_hash VARCHAR(128), user_agent TEXT, evidence JSONB NOT NULL DEFAULT '{}', created_at TIMESTAMPTZ(3) NOT NULL DEFAULT now(), CHECK(user_id IS NOT NULL OR lead_id IS NOT NULL));
CREATE INDEX consent_subject_idx ON consent_records(user_id,lead_id,created_at DESC);
CREATE TABLE marketing_preferences (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id UUID REFERENCES users(id) ON DELETE CASCADE, lead_id UUID REFERENCES leads(id) ON DELETE CASCADE, channel VARCHAR(20) NOT NULL CHECK(channel IN ('EMAIL','SMS','TELEGRAM','WHATSAPP','PUSH')), subscribed BOOLEAN NOT NULL DEFAULT false, source VARCHAR(60), confirmed_at TIMESTAMPTZ(3), unsubscribed_at TIMESTAMPTZ(3), updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT now(), CHECK(user_id IS NOT NULL OR lead_id IS NOT NULL));
CREATE UNIQUE INDEX marketing_user_channel_unique ON marketing_preferences(user_id,channel) WHERE user_id IS NOT NULL;
CREATE UNIQUE INDEX marketing_lead_channel_unique ON marketing_preferences(lead_id,channel) WHERE lead_id IS NOT NULL;

CREATE TABLE graduates (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id UUID REFERENCES users(id) ON DELETE SET NULL, slug VARCHAR(180) NOT NULL UNIQUE, photo_media_id UUID REFERENCES media_assets(id), current_job_title VARCHAR(180), company_id UUID REFERENCES companies(id), graduation_year SMALLINT CHECK(graduation_year BETWEEN 2000 AND 2200), is_featured BOOLEAN NOT NULL DEFAULT false, status "PublicationStatus" NOT NULL DEFAULT 'DRAFT', consent_expires_at TIMESTAMPTZ(3), published_at TIMESTAMPTZ(3), created_at TIMESTAMPTZ(3) NOT NULL DEFAULT now());
CREATE TABLE graduate_translations (graduate_id UUID NOT NULL REFERENCES graduates(id) ON DELETE CASCADE, locale VARCHAR(10) NOT NULL CHECK(locale IN ('ru','ky','en')), name TEXT NOT NULL, story TEXT, quote TEXT, PRIMARY KEY(graduate_id,locale));
CREATE TABLE graduate_courses (graduate_id UUID NOT NULL REFERENCES graduates(id) ON DELETE CASCADE, course_id UUID NOT NULL REFERENCES courses(id) ON DELETE RESTRICT, PRIMARY KEY(graduate_id,course_id));
CREATE TABLE student_stories (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), graduate_id UUID REFERENCES graduates(id) ON DELETE SET NULL, slug VARCHAR(180) NOT NULL UNIQUE, cover_media_id UUID REFERENCES media_assets(id), video_media_id UUID REFERENCES media_assets(id), status "PublicationStatus" NOT NULL DEFAULT 'DRAFT', published_at TIMESTAMPTZ(3), created_at TIMESTAMPTZ(3) NOT NULL DEFAULT now());
CREATE TABLE student_story_translations (story_id UUID NOT NULL REFERENCES student_stories(id) ON DELETE CASCADE, locale VARCHAR(10) NOT NULL CHECK(locale IN ('ru','ky','en')), title TEXT NOT NULL, excerpt TEXT, body_json JSONB NOT NULL DEFAULT '[]', seo_title TEXT, seo_description TEXT, PRIMARY KEY(story_id,locale));
CREATE TABLE reviews (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id UUID REFERENCES users(id) ON DELETE SET NULL, course_id UUID REFERENCES courses(id) ON DELETE SET NULL, group_id UUID REFERENCES "groups"(id) ON DELETE SET NULL, rating SMALLINT NOT NULL CHECK(rating BETWEEN 1 AND 5), status VARCHAR(20) NOT NULL DEFAULT 'PENDING' CHECK(status IN ('PENDING','APPROVED','REJECTED','HIDDEN')), author_name VARCHAR(180), consent_to_publish BOOLEAN NOT NULL DEFAULT false, moderated_by UUID REFERENCES users(id), moderated_at TIMESTAMPTZ(3), created_at TIMESTAMPTZ(3) NOT NULL DEFAULT now());
CREATE TABLE review_translations (review_id UUID NOT NULL REFERENCES reviews(id) ON DELETE CASCADE, locale VARCHAR(10) NOT NULL CHECK(locale IN ('ru','ky','en')), body TEXT NOT NULL, PRIMARY KEY(review_id,locale));

CREATE TABLE site_pages (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), slug VARCHAR(220) NOT NULL UNIQUE, template VARCHAR(80) NOT NULL DEFAULT 'default', status "PublicationStatus" NOT NULL DEFAULT 'DRAFT', published_at TIMESTAMPTZ(3), created_by UUID REFERENCES users(id), updated_by UUID REFERENCES users(id), created_at TIMESTAMPTZ(3) NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT now());
CREATE TABLE site_page_translations (page_id UUID NOT NULL REFERENCES site_pages(id) ON DELETE CASCADE, locale VARCHAR(10) NOT NULL CHECK(locale IN ('ru','ky','en')), title TEXT NOT NULL, content_json JSONB NOT NULL DEFAULT '[]', seo_title TEXT, seo_description TEXT, og_media_id UUID REFERENCES media_assets(id), PRIMARY KEY(page_id,locale));
CREATE TABLE landing_sections (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), page_id UUID NOT NULL REFERENCES site_pages(id) ON DELETE CASCADE, section_key VARCHAR(100) NOT NULL, component VARCHAR(100) NOT NULL, position INTEGER NOT NULL DEFAULT 0, status "PublicationStatus" NOT NULL DEFAULT 'DRAFT', settings JSONB NOT NULL DEFAULT '{}', starts_at TIMESTAMPTZ(3), ends_at TIMESTAMPTZ(3), UNIQUE(page_id,section_key));
CREATE TABLE landing_section_translations (section_id UUID NOT NULL REFERENCES landing_sections(id) ON DELETE CASCADE, locale VARCHAR(10) NOT NULL CHECK(locale IN ('ru','ky','en')), content_json JSONB NOT NULL DEFAULT '{}', PRIMARY KEY(section_id,locale));
CREATE TABLE banners (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), placement VARCHAR(80) NOT NULL, media_id UUID REFERENCES media_assets(id), link_url TEXT, status "PublicationStatus" NOT NULL DEFAULT 'DRAFT', starts_at TIMESTAMPTZ(3), ends_at TIMESTAMPTZ(3), sort_order INTEGER NOT NULL DEFAULT 0);
CREATE TABLE banner_translations (banner_id UUID NOT NULL REFERENCES banners(id) ON DELETE CASCADE, locale VARCHAR(10) NOT NULL CHECK(locale IN ('ru','ky','en')), title TEXT, subtitle TEXT, cta_label TEXT, PRIMARY KEY(banner_id,locale));
CREATE TABLE faq_categories (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), slug VARCHAR(160) NOT NULL UNIQUE, sort_order INTEGER NOT NULL DEFAULT 0, status "PublicationStatus" NOT NULL DEFAULT 'DRAFT');
CREATE TABLE faq_category_translations (category_id UUID NOT NULL REFERENCES faq_categories(id) ON DELETE CASCADE, locale VARCHAR(10) NOT NULL CHECK(locale IN ('ru','ky','en')), name TEXT NOT NULL, PRIMARY KEY(category_id,locale));
CREATE TABLE faq_items (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), category_id UUID REFERENCES faq_categories(id) ON DELETE SET NULL, sort_order INTEGER NOT NULL DEFAULT 0, status "PublicationStatus" NOT NULL DEFAULT 'DRAFT', created_at TIMESTAMPTZ(3) NOT NULL DEFAULT now());
CREATE TABLE faq_item_translations (item_id UUID NOT NULL REFERENCES faq_items(id) ON DELETE CASCADE, locale VARCHAR(10) NOT NULL CHECK(locale IN ('ru','ky','en')), question TEXT NOT NULL, answer TEXT NOT NULL, PRIMARY KEY(item_id,locale));

CREATE TABLE blog_categories (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), slug VARCHAR(160) NOT NULL UNIQUE, status "PublicationStatus" NOT NULL DEFAULT 'DRAFT');
CREATE TABLE blog_category_translations (category_id UUID NOT NULL REFERENCES blog_categories(id) ON DELETE CASCADE, locale VARCHAR(10) NOT NULL CHECK(locale IN ('ru','ky','en')), name TEXT NOT NULL, PRIMARY KEY(category_id,locale));
CREATE TABLE blog_posts (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), slug VARCHAR(220) NOT NULL UNIQUE, author_id UUID REFERENCES users(id) ON DELETE SET NULL, cover_media_id UUID REFERENCES media_assets(id), status "PublicationStatus" NOT NULL DEFAULT 'DRAFT', published_at TIMESTAMPTZ(3), created_at TIMESTAMPTZ(3) NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT now());
CREATE TABLE blog_post_translations (post_id UUID NOT NULL REFERENCES blog_posts(id) ON DELETE CASCADE, locale VARCHAR(10) NOT NULL CHECK(locale IN ('ru','ky','en')), title TEXT NOT NULL, excerpt TEXT, body_json JSONB NOT NULL DEFAULT '[]', seo_title TEXT, seo_description TEXT, PRIMARY KEY(post_id,locale));
CREATE TABLE blog_post_categories (post_id UUID NOT NULL REFERENCES blog_posts(id) ON DELETE CASCADE, category_id UUID NOT NULL REFERENCES blog_categories(id) ON DELETE CASCADE, PRIMARY KEY(post_id,category_id));
CREATE INDEX blog_posts_published_idx ON blog_posts(published_at DESC) WHERE status='PUBLISHED';

CREATE TABLE events (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), slug VARCHAR(200) NOT NULL UNIQUE, format "CourseFormat" NOT NULL, branch_id UUID REFERENCES branches(id) ON DELETE SET NULL, cover_media_id UUID REFERENCES media_assets(id), starts_at TIMESTAMPTZ(3) NOT NULL, ends_at TIMESTAMPTZ(3), capacity INTEGER CHECK(capacity>0), registration_closes_at TIMESTAMPTZ(3), status "PublicationStatus" NOT NULL DEFAULT 'DRAFT', created_at TIMESTAMPTZ(3) NOT NULL DEFAULT now(), CHECK(ends_at IS NULL OR ends_at>starts_at));
CREATE TABLE event_translations (event_id UUID NOT NULL REFERENCES events(id) ON DELETE CASCADE, locale VARCHAR(10) NOT NULL CHECK(locale IN ('ru','ky','en')), title TEXT NOT NULL, short_description TEXT, description TEXT, location_label TEXT, PRIMARY KEY(event_id,locale));
CREATE TABLE event_registrations (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), event_id UUID NOT NULL REFERENCES events(id) ON DELETE RESTRICT, user_id UUID REFERENCES users(id) ON DELETE SET NULL, lead_id UUID REFERENCES leads(id) ON DELETE SET NULL, status VARCHAR(20) NOT NULL DEFAULT 'REGISTERED' CHECK(status IN ('REGISTERED','CONFIRMED','ATTENDED','NO_SHOW','CANCELLED')), registered_at TIMESTAMPTZ(3) NOT NULL DEFAULT now(), CHECK(user_id IS NOT NULL OR lead_id IS NOT NULL));
CREATE TABLE social_links (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), platform VARCHAR(40) NOT NULL, url TEXT NOT NULL, status "PublicationStatus" NOT NULL DEFAULT 'DRAFT', sort_order INTEGER NOT NULL DEFAULT 0);
CREATE TABLE site_settings (key VARCHAR(160) PRIMARY KEY, value JSONB NOT NULL, is_public BOOLEAN NOT NULL DEFAULT false, updated_by UUID REFERENCES users(id), updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT now());
CREATE TABLE content_revisions (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), entity_type VARCHAR(80) NOT NULL, entity_id UUID NOT NULL, revision INTEGER NOT NULL, snapshot JSONB NOT NULL, created_by UUID REFERENCES users(id), created_at TIMESTAMPTZ(3) NOT NULL DEFAULT now(), UNIQUE(entity_type,entity_id,revision));

CREATE TABLE conversations (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), type VARCHAR(30) NOT NULL CHECK(type IN ('DIRECT','GROUP','COURSE','SUPPORT')), title VARCHAR(240), created_by UUID REFERENCES users(id), created_at TIMESTAMPTZ(3) NOT NULL DEFAULT now(), archived_at TIMESTAMPTZ(3));
CREATE TABLE conversation_participants (conversation_id UUID NOT NULL REFERENCES conversations(id) ON DELETE CASCADE, user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE, role VARCHAR(20) NOT NULL DEFAULT 'MEMBER', joined_at TIMESTAMPTZ(3) NOT NULL DEFAULT now(), left_at TIMESTAMPTZ(3), last_read_at TIMESTAMPTZ(3), PRIMARY KEY(conversation_id,user_id));
CREATE TABLE messages (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), conversation_id UUID NOT NULL REFERENCES conversations(id) ON DELETE CASCADE, sender_id UUID REFERENCES users(id) ON DELETE SET NULL, reply_to_id UUID REFERENCES messages(id) ON DELETE SET NULL, body TEXT, status VARCHAR(20) NOT NULL DEFAULT 'VISIBLE', created_at TIMESTAMPTZ(3) NOT NULL DEFAULT now(), edited_at TIMESTAMPTZ(3), deleted_at TIMESTAMPTZ(3));
CREATE INDEX messages_conversation_idx ON messages(conversation_id,created_at DESC);
CREATE TABLE message_attachments (message_id UUID NOT NULL REFERENCES messages(id) ON DELETE CASCADE, media_id UUID NOT NULL REFERENCES media_assets(id) ON DELETE RESTRICT, PRIMARY KEY(message_id,media_id));

CREATE TABLE mentor_help_requests (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), enrollment_id UUID NOT NULL REFERENCES enrollments(id) ON DELETE CASCADE, lesson_id UUID REFERENCES lessons(id) ON DELETE SET NULL, student_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE, mentor_id UUID REFERENCES users(id) ON DELETE SET NULL, title VARCHAR(240) NOT NULL, description TEXT NOT NULL, priority VARCHAR(10) NOT NULL DEFAULT 'NORMAL', status VARCHAR(20) NOT NULL DEFAULT 'OPEN' CHECK(status IN ('OPEN','ASSIGNED','IN_PROGRESS','RESOLVED','CLOSED')), created_at TIMESTAMPTZ(3) NOT NULL DEFAULT now(), resolved_at TIMESTAMPTZ(3));
CREATE TABLE mentor_recommendations (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), mentor_id UUID NOT NULL REFERENCES users(id) ON DELETE RESTRICT, student_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE, enrollment_id UUID REFERENCES enrollments(id) ON DELETE CASCADE, title VARCHAR(240) NOT NULL, body TEXT NOT NULL, resource_url TEXT, created_at TIMESTAMPTZ(3) NOT NULL DEFAULT now());
CREATE TABLE mentor_availability (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), mentor_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE, weekday SMALLINT CHECK(weekday BETWEEN 1 AND 7), starts_at TIME NOT NULL, ends_at TIME NOT NULL, timezone VARCHAR(64) NOT NULL DEFAULT 'Asia/Bishkek', valid_from DATE, valid_until DATE, CHECK(ends_at>starts_at));
CREATE TABLE mentor_sessions (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), mentor_id UUID NOT NULL REFERENCES users(id) ON DELETE RESTRICT, student_id UUID NOT NULL REFERENCES users(id) ON DELETE RESTRICT, enrollment_id UUID REFERENCES enrollments(id) ON DELETE SET NULL, starts_at TIMESTAMPTZ(3) NOT NULL, ends_at TIMESTAMPTZ(3) NOT NULL, status VARCHAR(20) NOT NULL DEFAULT 'SCHEDULED', meeting_url TEXT, student_note TEXT, mentor_note TEXT, created_at TIMESTAMPTZ(3) NOT NULL DEFAULT now(), CHECK(ends_at>starts_at));

CREATE TABLE support_categories (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), code VARCHAR(80) NOT NULL UNIQUE, name VARCHAR(160) NOT NULL, is_active BOOLEAN NOT NULL DEFAULT true);
CREATE TABLE support_tickets (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), ticket_number VARCHAR(40) NOT NULL UNIQUE, user_id UUID REFERENCES users(id) ON DELETE SET NULL, category_id UUID REFERENCES support_categories(id) ON DELETE SET NULL, assignee_id UUID REFERENCES users(id) ON DELETE SET NULL, subject VARCHAR(240) NOT NULL, priority VARCHAR(10) NOT NULL DEFAULT 'NORMAL', status VARCHAR(20) NOT NULL DEFAULT 'OPEN' CHECK(status IN ('OPEN','IN_PROGRESS','WAITING_USER','RESOLVED','CLOSED')), created_at TIMESTAMPTZ(3) NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT now(), resolved_at TIMESTAMPTZ(3));
CREATE TABLE support_messages (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), ticket_id UUID NOT NULL REFERENCES support_tickets(id) ON DELETE CASCADE, author_id UUID REFERENCES users(id) ON DELETE SET NULL, body TEXT NOT NULL, is_internal BOOLEAN NOT NULL DEFAULT false, created_at TIMESTAMPTZ(3) NOT NULL DEFAULT now());
CREATE TABLE support_message_attachments (message_id UUID NOT NULL REFERENCES support_messages(id) ON DELETE CASCADE, media_id UUID NOT NULL REFERENCES media_assets(id) ON DELETE RESTRICT, PRIMARY KEY(message_id,media_id));
CREATE TABLE help_articles (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), slug VARCHAR(220) NOT NULL UNIQUE, category_id UUID REFERENCES support_categories(id) ON DELETE SET NULL, status "PublicationStatus" NOT NULL DEFAULT 'DRAFT', sort_order INTEGER NOT NULL DEFAULT 0, published_at TIMESTAMPTZ(3));
CREATE TABLE help_article_translations (article_id UUID NOT NULL REFERENCES help_articles(id) ON DELETE CASCADE, locale VARCHAR(10) NOT NULL CHECK(locale IN ('ru','ky','en')), title TEXT NOT NULL, body_json JSONB NOT NULL DEFAULT '[]', PRIMARY KEY(article_id,locale));

CREATE TABLE notification_templates (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), code VARCHAR(120) NOT NULL UNIQUE, channel VARCHAR(20) NOT NULL CHECK(channel IN ('EMAIL','SMS','TELEGRAM','PUSH','IN_APP')), status "PublicationStatus" NOT NULL DEFAULT 'DRAFT', variables JSONB NOT NULL DEFAULT '[]');
CREATE TABLE notification_template_translations (template_id UUID NOT NULL REFERENCES notification_templates(id) ON DELETE CASCADE, locale VARCHAR(10) NOT NULL CHECK(locale IN ('ru','ky','en')), subject TEXT, body TEXT NOT NULL, PRIMARY KEY(template_id,locale));
CREATE TABLE notifications (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE, type VARCHAR(80) NOT NULL, title TEXT NOT NULL, body TEXT NOT NULL, action_url TEXT, payload JSONB NOT NULL DEFAULT '{}', read_at TIMESTAMPTZ(3), created_at TIMESTAMPTZ(3) NOT NULL DEFAULT now());
CREATE INDEX notifications_unread_idx ON notifications(user_id,created_at DESC) WHERE read_at IS NULL;
CREATE TABLE notification_deliveries (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), notification_id UUID REFERENCES notifications(id) ON DELETE CASCADE, template_id UUID REFERENCES notification_templates(id) ON DELETE SET NULL, user_id UUID REFERENCES users(id) ON DELETE CASCADE, channel VARCHAR(20) NOT NULL, recipient VARCHAR(255) NOT NULL, provider VARCHAR(50), provider_message_id VARCHAR(255), status VARCHAR(20) NOT NULL DEFAULT 'QUEUED', attempt_count INTEGER NOT NULL DEFAULT 0, last_error TEXT, scheduled_at TIMESTAMPTZ(3), sent_at TIMESTAMPTZ(3), delivered_at TIMESTAMPTZ(3), created_at TIMESTAMPTZ(3) NOT NULL DEFAULT now());
CREATE TABLE notification_preferences (user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE, event_type VARCHAR(80) NOT NULL, channel VARCHAR(20) NOT NULL, enabled BOOLEAN NOT NULL DEFAULT true, PRIMARY KEY(user_id,event_type,channel));
CREATE TABLE telegram_subscriptions (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE, telegram_user_id BIGINT NOT NULL UNIQUE, chat_id BIGINT NOT NULL, username VARCHAR(100), verified_at TIMESTAMPTZ(3), disabled_at TIMESTAMPTZ(3), created_at TIMESTAMPTZ(3) NOT NULL DEFAULT now());
CREATE TABLE staff_notification_destinations (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), event_type VARCHAR(80) NOT NULL, channel VARCHAR(20) NOT NULL, destination VARCHAR(255) NOT NULL, is_active BOOLEAN NOT NULL DEFAULT true, UNIQUE(event_type,channel,destination));
CREATE TABLE email_suppressions (email CITEXT PRIMARY KEY, reason VARCHAR(80) NOT NULL, provider VARCHAR(50), created_at TIMESTAMPTZ(3) NOT NULL DEFAULT now());

COMMIT;
