BEGIN;

CREATE TYPE "AssignmentSubmissionStatus" AS ENUM ('DRAFT','SUBMITTED','UNDER_REVIEW','CHANGES_REQUESTED','ACCEPTED','REJECTED');
CREATE TYPE "TestAttemptStatus" AS ENUM ('IN_PROGRESS','SUBMITTED','GRADED','EXPIRED','CANCELLED');

CREATE TABLE enrollments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id UUID NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  course_id UUID NOT NULL REFERENCES courses(id) ON DELETE RESTRICT, group_id UUID REFERENCES "groups"(id) ON DELETE RESTRICT,
  tariff_id UUID REFERENCES tariffs(id) ON DELETE RESTRICT, status "EnrollmentStatus" NOT NULL DEFAULT 'PENDING',
  enrolled_at TIMESTAMPTZ(3) NOT NULL DEFAULT now(), starts_at TIMESTAMPTZ(3), access_expires_at TIMESTAMPTZ(3),
  completed_at TIMESTAMPTZ(3), source VARCHAR(40), created_at TIMESTAMPTZ(3) NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX enrollments_user_group_active_unique ON enrollments(user_id,group_id) WHERE group_id IS NOT NULL AND status IN ('PENDING','ACTIVE','PAUSED');
CREATE INDEX enrollments_user_status_idx ON enrollments(user_id,status);
CREATE INDEX enrollments_group_status_idx ON enrollments(group_id,status);

CREATE TABLE enrollment_history (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), enrollment_id UUID NOT NULL REFERENCES enrollments(id) ON DELETE CASCADE, from_status "EnrollmentStatus", to_status "EnrollmentStatus" NOT NULL, reason TEXT, changed_by UUID REFERENCES users(id), created_at TIMESTAMPTZ(3) NOT NULL DEFAULT now());
CREATE TABLE group_waitlist (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), group_id UUID NOT NULL REFERENCES "groups"(id) ON DELETE CASCADE, user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE, priority INTEGER NOT NULL DEFAULT 0, status VARCHAR(20) NOT NULL DEFAULT 'WAITING' CHECK(status IN ('WAITING','INVITED','ENROLLED','EXPIRED','CANCELLED')), invited_at TIMESTAMPTZ(3), expires_at TIMESTAMPTZ(3), created_at TIMESTAMPTZ(3) NOT NULL DEFAULT now(), UNIQUE(group_id,user_id));
CREATE TABLE attendance_records (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), class_session_id UUID NOT NULL REFERENCES class_sessions(id) ON DELETE CASCADE, enrollment_id UUID NOT NULL REFERENCES enrollments(id) ON DELETE RESTRICT, status "AttendanceStatus" NOT NULL, minutes_late INTEGER CHECK(minutes_late>=0), note TEXT, marked_by UUID REFERENCES users(id), marked_at TIMESTAMPTZ(3) NOT NULL DEFAULT now(), UNIQUE(class_session_id,enrollment_id));

CREATE TABLE lesson_progress (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), enrollment_id UUID NOT NULL REFERENCES enrollments(id) ON DELETE CASCADE, lesson_id UUID NOT NULL REFERENCES lessons(id) ON DELETE RESTRICT, status VARCHAR(20) NOT NULL DEFAULT 'NOT_STARTED' CHECK(status IN ('NOT_STARTED','IN_PROGRESS','COMPLETED','SKIPPED')), percent NUMERIC(5,2) NOT NULL DEFAULT 0 CHECK(percent BETWEEN 0 AND 100), seconds_spent INTEGER NOT NULL DEFAULT 0 CHECK(seconds_spent>=0), last_position_json JSONB NOT NULL DEFAULT '{}', started_at TIMESTAMPTZ(3), completed_at TIMESTAMPTZ(3), updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT now(), UNIQUE(enrollment_id,lesson_id));
CREATE TABLE module_progress (enrollment_id UUID NOT NULL REFERENCES enrollments(id) ON DELETE CASCADE, module_id UUID NOT NULL REFERENCES course_modules(id) ON DELETE RESTRICT, percent NUMERIC(5,2) NOT NULL DEFAULT 0 CHECK(percent BETWEEN 0 AND 100), completed_at TIMESTAMPTZ(3), updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT now(), PRIMARY KEY(enrollment_id,module_id));
CREATE TABLE course_progress (enrollment_id UUID PRIMARY KEY REFERENCES enrollments(id) ON DELETE CASCADE, percent NUMERIC(5,2) NOT NULL DEFAULT 0 CHECK(percent BETWEEN 0 AND 100), required_lessons_total INTEGER NOT NULL DEFAULT 0, required_lessons_completed INTEGER NOT NULL DEFAULT 0, updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT now());
CREATE TABLE learning_events (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), enrollment_id UUID NOT NULL REFERENCES enrollments(id) ON DELETE CASCADE, user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE, lesson_id UUID REFERENCES lessons(id) ON DELETE SET NULL, event_type VARCHAR(50) NOT NULL, payload JSONB NOT NULL DEFAULT '{}', occurred_at TIMESTAMPTZ(3) NOT NULL DEFAULT now());
CREATE INDEX learning_events_user_time_idx ON learning_events(user_id,occurred_at DESC);
CREATE TABLE lesson_comments (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), lesson_id UUID NOT NULL REFERENCES lessons(id) ON DELETE CASCADE, user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE, parent_id UUID REFERENCES lesson_comments(id) ON DELETE CASCADE, body TEXT NOT NULL, status VARCHAR(20) NOT NULL DEFAULT 'VISIBLE', created_at TIMESTAMPTZ(3) NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT now());
CREATE TABLE lesson_bookmarks (user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE, lesson_id UUID NOT NULL REFERENCES lessons(id) ON DELETE CASCADE, note TEXT, created_at TIMESTAMPTZ(3) NOT NULL DEFAULT now(), PRIMARY KEY(user_id,lesson_id));
CREATE TABLE media_access_grants (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), media_id UUID NOT NULL REFERENCES media_assets(id) ON DELETE CASCADE, user_id UUID REFERENCES users(id) ON DELETE CASCADE, enrollment_id UUID REFERENCES enrollments(id) ON DELETE CASCADE, expires_at TIMESTAMPTZ(3) NOT NULL, created_at TIMESTAMPTZ(3) NOT NULL DEFAULT now(), CHECK(user_id IS NOT NULL OR enrollment_id IS NOT NULL));

CREATE TABLE assignments (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), lesson_id UUID REFERENCES lessons(id) ON DELETE RESTRICT, course_version_id UUID NOT NULL REFERENCES course_versions(id) ON DELETE RESTRICT, status "PublicationStatus" NOT NULL DEFAULT 'DRAFT', max_score NUMERIC(8,2) NOT NULL DEFAULT 100 CHECK(max_score>0), passing_score NUMERIC(8,2) NOT NULL DEFAULT 60 CHECK(passing_score>=0), attempts_limit INTEGER CHECK(attempts_limit>0), due_offset_days INTEGER, allow_late BOOLEAN NOT NULL DEFAULT false, created_by UUID REFERENCES users(id), created_at TIMESTAMPTZ(3) NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT now(), CHECK(passing_score<=max_score));
CREATE TABLE assignment_translations (assignment_id UUID NOT NULL REFERENCES assignments(id) ON DELETE CASCADE, locale VARCHAR(10) NOT NULL CHECK(locale IN ('ru','ky','en')), title TEXT NOT NULL, instructions TEXT NOT NULL, PRIMARY KEY(assignment_id,locale));
CREATE TABLE assignment_attachments (assignment_id UUID NOT NULL REFERENCES assignments(id) ON DELETE CASCADE, media_id UUID NOT NULL REFERENCES media_assets(id) ON DELETE RESTRICT, position INTEGER NOT NULL DEFAULT 0, PRIMARY KEY(assignment_id,media_id));
CREATE TABLE assignment_rubric_items (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), assignment_id UUID NOT NULL REFERENCES assignments(id) ON DELETE CASCADE, max_score NUMERIC(8,2) NOT NULL CHECK(max_score>0), position INTEGER NOT NULL DEFAULT 0);
CREATE TABLE assignment_rubric_item_translations (item_id UUID NOT NULL REFERENCES assignment_rubric_items(id) ON DELETE CASCADE, locale VARCHAR(10) NOT NULL CHECK(locale IN ('ru','ky','en')), title TEXT NOT NULL, description TEXT, PRIMARY KEY(item_id,locale));
CREATE TABLE assignment_states (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), assignment_id UUID NOT NULL REFERENCES assignments(id) ON DELETE CASCADE, enrollment_id UUID NOT NULL REFERENCES enrollments(id) ON DELETE CASCADE, due_at TIMESTAMPTZ(3), attempts_used INTEGER NOT NULL DEFAULT 0, best_score NUMERIC(8,2), passed_at TIMESTAMPTZ(3), UNIQUE(assignment_id,enrollment_id));
CREATE TABLE assignment_submissions (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), assignment_state_id UUID NOT NULL REFERENCES assignment_states(id) ON DELETE CASCADE, attempt_number INTEGER NOT NULL CHECK(attempt_number>0), status "AssignmentSubmissionStatus" NOT NULL DEFAULT 'DRAFT', text_answer TEXT, submitted_at TIMESTAMPTZ(3), reviewed_at TIMESTAMPTZ(3), reviewed_by UUID REFERENCES users(id), score NUMERIC(8,2), created_at TIMESTAMPTZ(3) NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT now(), UNIQUE(assignment_state_id,attempt_number));
CREATE TABLE submission_files (submission_id UUID NOT NULL REFERENCES assignment_submissions(id) ON DELETE CASCADE, media_id UUID NOT NULL REFERENCES media_assets(id) ON DELETE RESTRICT, PRIMARY KEY(submission_id,media_id));
CREATE TABLE submission_feedback (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), submission_id UUID NOT NULL REFERENCES assignment_submissions(id) ON DELETE CASCADE, author_id UUID NOT NULL REFERENCES users(id) ON DELETE RESTRICT, body TEXT NOT NULL, is_internal BOOLEAN NOT NULL DEFAULT false, created_at TIMESTAMPTZ(3) NOT NULL DEFAULT now());
CREATE TABLE submission_rubric_scores (submission_id UUID NOT NULL REFERENCES assignment_submissions(id) ON DELETE CASCADE, rubric_item_id UUID NOT NULL REFERENCES assignment_rubric_items(id) ON DELETE RESTRICT, score NUMERIC(8,2) NOT NULL CHECK(score>=0), note TEXT, PRIMARY KEY(submission_id,rubric_item_id));

CREATE TABLE tests (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), lesson_id UUID REFERENCES lessons(id) ON DELETE RESTRICT, course_version_id UUID NOT NULL REFERENCES course_versions(id) ON DELETE RESTRICT, kind VARCHAR(20) NOT NULL DEFAULT 'QUIZ' CHECK(kind IN ('QUIZ','EXAM','DIAGNOSTIC','SURVEY')), status "PublicationStatus" NOT NULL DEFAULT 'DRAFT', duration_minutes INTEGER CHECK(duration_minutes>0), attempts_limit INTEGER CHECK(attempts_limit>0), passing_score NUMERIC(5,2) CHECK(passing_score BETWEEN 0 AND 100), shuffle_questions BOOLEAN NOT NULL DEFAULT false, show_answers BOOLEAN NOT NULL DEFAULT false, created_by UUID REFERENCES users(id), created_at TIMESTAMPTZ(3) NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT now());
CREATE TABLE test_translations (test_id UUID NOT NULL REFERENCES tests(id) ON DELETE CASCADE, locale VARCHAR(10) NOT NULL CHECK(locale IN ('ru','ky','en')), title TEXT NOT NULL, instructions TEXT, PRIMARY KEY(test_id,locale));
CREATE TABLE question_bank_items (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), course_id UUID NOT NULL REFERENCES courses(id) ON DELETE RESTRICT, type VARCHAR(30) NOT NULL CHECK(type IN ('SINGLE_CHOICE','MULTIPLE_CHOICE','TRUE_FALSE','SHORT_TEXT','LONG_TEXT','NUMBER','MATCHING','ORDERING')), difficulty SMALLINT CHECK(difficulty BETWEEN 1 AND 5), points NUMERIC(8,2) NOT NULL DEFAULT 1 CHECK(points>=0), explanation TEXT, answer_key_json JSONB NOT NULL DEFAULT '{}', status "PublicationStatus" NOT NULL DEFAULT 'DRAFT', created_by UUID REFERENCES users(id), created_at TIMESTAMPTZ(3) NOT NULL DEFAULT now());
CREATE TABLE question_translations (question_id UUID NOT NULL REFERENCES question_bank_items(id) ON DELETE CASCADE, locale VARCHAR(10) NOT NULL CHECK(locale IN ('ru','ky','en')), prompt TEXT NOT NULL, explanation TEXT, PRIMARY KEY(question_id,locale));
CREATE TABLE question_options (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), question_id UUID NOT NULL REFERENCES question_bank_items(id) ON DELETE CASCADE, key VARCHAR(50) NOT NULL, is_correct BOOLEAN NOT NULL DEFAULT false, position INTEGER NOT NULL DEFAULT 0, UNIQUE(question_id,key));
CREATE TABLE question_option_translations (option_id UUID NOT NULL REFERENCES question_options(id) ON DELETE CASCADE, locale VARCHAR(10) NOT NULL CHECK(locale IN ('ru','ky','en')), label TEXT NOT NULL, PRIMARY KEY(option_id,locale));
CREATE TABLE test_questions (test_id UUID NOT NULL REFERENCES tests(id) ON DELETE CASCADE, question_id UUID NOT NULL REFERENCES question_bank_items(id) ON DELETE RESTRICT, position INTEGER NOT NULL, points_override NUMERIC(8,2), is_required BOOLEAN NOT NULL DEFAULT true, PRIMARY KEY(test_id,question_id), UNIQUE(test_id,position));
CREATE TABLE test_attempts (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), test_id UUID NOT NULL REFERENCES tests(id) ON DELETE RESTRICT, enrollment_id UUID NOT NULL REFERENCES enrollments(id) ON DELETE CASCADE, attempt_number INTEGER NOT NULL CHECK(attempt_number>0), status "TestAttemptStatus" NOT NULL DEFAULT 'IN_PROGRESS', started_at TIMESTAMPTZ(3) NOT NULL DEFAULT now(), expires_at TIMESTAMPTZ(3), submitted_at TIMESTAMPTZ(3), graded_at TIMESTAMPTZ(3), score NUMERIC(8,2), percent NUMERIC(5,2) CHECK(percent BETWEEN 0 AND 100), passed BOOLEAN, UNIQUE(test_id,enrollment_id,attempt_number));
CREATE TABLE test_attempt_questions (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), attempt_id UUID NOT NULL REFERENCES test_attempts(id) ON DELETE CASCADE, question_id UUID NOT NULL REFERENCES question_bank_items(id) ON DELETE RESTRICT, position INTEGER NOT NULL, points NUMERIC(8,2) NOT NULL, question_snapshot JSONB NOT NULL, UNIQUE(attempt_id,position));
CREATE TABLE test_answers (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), attempt_question_id UUID NOT NULL REFERENCES test_attempt_questions(id) ON DELETE CASCADE, answer_json JSONB NOT NULL DEFAULT '{}', is_correct BOOLEAN, awarded_points NUMERIC(8,2), graded_by UUID REFERENCES users(id), answered_at TIMESTAMPTZ(3) NOT NULL DEFAULT now(), UNIQUE(attempt_question_id));
CREATE TABLE diagnostic_results (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), test_attempt_id UUID NOT NULL UNIQUE REFERENCES test_attempts(id) ON DELETE CASCADE, recommended_course_id UUID REFERENCES courses(id), recommended_level "CourseLevel", summary_json JSONB NOT NULL DEFAULT '{}', created_at TIMESTAMPTZ(3) NOT NULL DEFAULT now());

CREATE TABLE projects (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), enrollment_id UUID NOT NULL REFERENCES enrollments(id) ON DELETE CASCADE, title VARCHAR(240) NOT NULL, description TEXT, repository_url TEXT, demo_url TEXT, status VARCHAR(24) NOT NULL DEFAULT 'DRAFT' CHECK(status IN ('DRAFT','SUBMITTED','UNDER_REVIEW','CHANGES_REQUESTED','ACCEPTED','REJECTED','PUBLISHED')), submitted_at TIMESTAMPTZ(3), published_at TIMESTAMPTZ(3), created_at TIMESTAMPTZ(3) NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT now());
CREATE TABLE project_files (project_id UUID NOT NULL REFERENCES projects(id) ON DELETE CASCADE, media_id UUID NOT NULL REFERENCES media_assets(id) ON DELETE RESTRICT, PRIMARY KEY(project_id,media_id));
CREATE TABLE project_reviews (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), project_id UUID NOT NULL REFERENCES projects(id) ON DELETE CASCADE, reviewer_id UUID NOT NULL REFERENCES users(id) ON DELETE RESTRICT, decision VARCHAR(24) NOT NULL CHECK(decision IN ('CHANGES_REQUESTED','ACCEPTED','REJECTED')), score NUMERIC(8,2), feedback TEXT, created_at TIMESTAMPTZ(3) NOT NULL DEFAULT now());

CREATE TABLE certificate_templates (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), course_id UUID REFERENCES courses(id) ON DELETE RESTRICT, name VARCHAR(180) NOT NULL, background_media_id UUID REFERENCES media_assets(id), layout_json JSONB NOT NULL DEFAULT '{}', status "PublicationStatus" NOT NULL DEFAULT 'DRAFT', created_at TIMESTAMPTZ(3) NOT NULL DEFAULT now());
CREATE TABLE certificate_requirements (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), course_id UUID NOT NULL REFERENCES courses(id) ON DELETE CASCADE, template_id UUID NOT NULL REFERENCES certificate_templates(id) ON DELETE RESTRICT, min_progress NUMERIC(5,2) NOT NULL DEFAULT 100 CHECK(min_progress BETWEEN 0 AND 100), min_test_score NUMERIC(5,2) CHECK(min_test_score BETWEEN 0 AND 100), require_project BOOLEAN NOT NULL DEFAULT false, UNIQUE(course_id,template_id));
CREATE TABLE certificates (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), enrollment_id UUID NOT NULL REFERENCES enrollments(id) ON DELETE RESTRICT, template_id UUID NOT NULL REFERENCES certificate_templates(id) ON DELETE RESTRICT, serial_number VARCHAR(100) NOT NULL UNIQUE, verification_code VARCHAR(100) NOT NULL UNIQUE, recipient_name VARCHAR(200) NOT NULL, course_title VARCHAR(240) NOT NULL, issued_at TIMESTAMPTZ(3) NOT NULL DEFAULT now(), revoked_at TIMESTAMPTZ(3), revocation_reason TEXT, pdf_media_id UUID REFERENCES media_assets(id), metadata JSONB NOT NULL DEFAULT '{}');
CREATE TABLE certificate_events (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), certificate_id UUID NOT NULL REFERENCES certificates(id) ON DELETE CASCADE, event_type VARCHAR(30) NOT NULL, actor_id UUID REFERENCES users(id), payload JSONB NOT NULL DEFAULT '{}', created_at TIMESTAMPTZ(3) NOT NULL DEFAULT now());

COMMIT;
