BEGIN;

CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE EXTENSION IF NOT EXISTS citext;

CREATE TYPE "PublicationStatus" AS ENUM ('DRAFT','REVIEW','PUBLISHED','ARCHIVED');
CREATE TYPE "UserStatus" AS ENUM ('INVITED','PENDING_VERIFICATION','ACTIVE','BLOCKED','ARCHIVED');
CREATE TYPE "CourseLevel" AS ENUM ('BEGINNER','ELEMENTARY','INTERMEDIATE','ADVANCED','ALL_LEVELS');
CREATE TYPE "CourseFormat" AS ENUM ('ONLINE','OFFLINE','HYBRID','SELF_PACED');
CREATE TYPE "GroupStatus" AS ENUM ('DRAFT','ENROLLMENT_OPEN','ACTIVE','COMPLETED','CANCELLED','ARCHIVED');
CREATE TYPE "EnrollmentStatus" AS ENUM ('PENDING','ACTIVE','PAUSED','COMPLETED','WITHDRAWN','TRANSFERRED','CANCELLED');
CREATE TYPE "AttendanceStatus" AS ENUM ('PRESENT','ABSENT','LATE','EXCUSED');

ALTER TABLE "users"
  ADD COLUMN "status" "UserStatus" NOT NULL DEFAULT 'PENDING_VERIFICATION',
  ADD COLUMN "first_name" VARCHAR(100), ADD COLUMN "last_name" VARCHAR(100),
  ADD COLUMN "display_name" VARCHAR(160), ADD COLUMN "email" CITEXT,
  ADD COLUMN "phone_e164" VARCHAR(20), ADD COLUMN "email_verified_at" TIMESTAMPTZ(3),
  ADD COLUMN "phone_verified_at" TIMESTAMPTZ(3), ADD COLUMN "preferred_locale" VARCHAR(10) NOT NULL DEFAULT 'ru',
  ADD COLUMN "timezone" VARCHAR(64) NOT NULL DEFAULT 'Asia/Bishkek',
  ADD COLUMN "last_login_at" TIMESTAMPTZ(3), ADD COLUMN "blocked_at" TIMESTAMPTZ(3),
  ADD COLUMN "archived_at" TIMESTAMPTZ(3),
  ADD CONSTRAINT "users_locale_check" CHECK (preferred_locale IN ('ru','ky','en'));
UPDATE users SET display_name = name WHERE display_name IS NULL AND name IS NOT NULL;
CREATE UNIQUE INDEX "users_email_unique" ON users(email) WHERE email IS NOT NULL;
CREATE UNIQUE INDEX "users_phone_unique" ON users(phone_e164) WHERE phone_e164 IS NOT NULL;
CREATE INDEX "users_status_created_idx" ON users(status, created_at DESC);

CREATE TABLE roles (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), code VARCHAR(20) NOT NULL UNIQUE, name VARCHAR(80) NOT NULL, created_at TIMESTAMPTZ(3) NOT NULL DEFAULT now());
INSERT INTO roles(code,name) VALUES ('ADMIN','Администратор'),('MENTOR','Ментор'),('STUDENT','Ученик');
ALTER TABLE user_roles ADD COLUMN role_id UUID REFERENCES roles(id), ADD COLUMN assigned_by UUID REFERENCES users(id), ADD COLUMN revoked_at TIMESTAMPTZ(3);
UPDATE user_roles ur SET role_id=r.id FROM roles r WHERE r.code=upper(ur.role::text);

CREATE TABLE permissions (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), code VARCHAR(80) NOT NULL UNIQUE, description TEXT, created_at TIMESTAMPTZ(3) NOT NULL DEFAULT now());
CREATE TABLE role_permissions (role_id UUID NOT NULL REFERENCES roles(id) ON DELETE CASCADE, permission_id UUID NOT NULL REFERENCES permissions(id) ON DELETE CASCADE, PRIMARY KEY(role_id,permission_id));
CREATE TABLE user_permissions (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE, permission_id UUID NOT NULL REFERENCES permissions(id) ON DELETE CASCADE, effect VARCHAR(5) NOT NULL CHECK(effect IN ('ALLOW','DENY')), granted_by UUID REFERENCES users(id), expires_at TIMESTAMPTZ(3), created_at TIMESTAMPTZ(3) NOT NULL DEFAULT now());
CREATE UNIQUE INDEX user_permissions_active_unique ON user_permissions(user_id,permission_id,effect) WHERE expires_at IS NULL;
INSERT INTO permissions(code,description) VALUES
('users.read','Просмотр пользователей'),('users.manage','Управление пользователями'),('roles.assign','Назначение ролей'),('permissions.manage','Управление правами'),('security.audit','Журнал безопасности'),
('content.read','Просмотр контента'),('content.write','Редактирование контента'),('content.review','Ревью контента'),('content.publish','Публикация контента'),('media.manage','Управление медиа'),
('courses.read','Просмотр курсов'),('courses.manage','Управление курсами'),('groups.manage','Управление группами'),('attendance.manage','Посещаемость'),('learning.publish','Публикация обучения'),
('assignments.manage','Управление заданиями'),('submissions.review','Проверка работ'),('tests.manage','Управление тестами'),('projects.review','Проверка проектов'),('certificates.issue','Выдача сертификатов'),
('leads.read','Просмотр заявок'),('leads.manage','Управление заявками'),('consultations.manage','Консультации'),('orders.read','Просмотр заказов'),
('finance.read','Финансовые данные'),('payments.reconcile','Сверка платежей'),('refunds.request','Запрос возврата'),('refunds.approve','Подтверждение возврата'),('prices.manage','Управление ценами'),
('messages.moderate','Модерация сообщений'),('support.manage','Центр помощи'),('notifications.send','Отправка уведомлений'),('integrations.manage','Интеграции'),
('reviews.moderate','Модерация отзывов'),('graduates.manage','Выпускники'),('events.manage','Мероприятия'),('analytics.read','Аналитика'),('analytics.export','Экспорт аналитики'),
('hackathons.manage','Управление хакатонами'),('hackathons.judge','Оценивание хакатонов'),('hackathons.publish_results','Публикация результатов'),('owner','Полный доступ владельца');

CREATE TABLE user_contacts (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE, type VARCHAR(16) NOT NULL CHECK(type IN ('EMAIL','PHONE')), value VARCHAR(255) NOT NULL, normalized_value VARCHAR(255) NOT NULL, is_primary BOOLEAN NOT NULL DEFAULT false, verified_at TIMESTAMPTZ(3), created_at TIMESTAMPTZ(3) NOT NULL DEFAULT now(), UNIQUE(type,normalized_value));
CREATE UNIQUE INDEX user_contacts_primary_unique ON user_contacts(user_id,type) WHERE is_primary;
CREATE TABLE oauth_accounts (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE, provider VARCHAR(40) NOT NULL, provider_account_id VARCHAR(255) NOT NULL, type VARCHAR(30) NOT NULL, access_token_encrypted TEXT, refresh_token_encrypted TEXT, expires_at TIMESTAMPTZ(3), scope TEXT, created_at TIMESTAMPTZ(3) NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT now(), UNIQUE(provider,provider_account_id));
CREATE TABLE sessions (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE, session_token_hash VARCHAR(128) NOT NULL UNIQUE, expires_at TIMESTAMPTZ(3) NOT NULL, revoked_at TIMESTAMPTZ(3), ip_hash VARCHAR(128), user_agent TEXT, last_seen_at TIMESTAMPTZ(3), created_at TIMESTAMPTZ(3) NOT NULL DEFAULT now());
CREATE INDEX sessions_active_idx ON sessions(user_id,expires_at) WHERE revoked_at IS NULL;
CREATE TABLE verification_tokens (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), identifier VARCHAR(255) NOT NULL, purpose VARCHAR(40) NOT NULL, token_hash VARCHAR(128) NOT NULL UNIQUE, expires_at TIMESTAMPTZ(3) NOT NULL, consumed_at TIMESTAMPTZ(3), attempt_count INTEGER NOT NULL DEFAULT 0, created_at TIMESTAMPTZ(3) NOT NULL DEFAULT now());
CREATE TABLE password_credentials (user_id UUID PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE, password_hash TEXT NOT NULL, password_changed_at TIMESTAMPTZ(3) NOT NULL DEFAULT now(), failed_attempts INTEGER NOT NULL DEFAULT 0, locked_until TIMESTAMPTZ(3));
CREATE TABLE mfa_methods (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE, type VARCHAR(20) NOT NULL, secret_encrypted TEXT NOT NULL, label VARCHAR(100), verified_at TIMESTAMPTZ(3), last_used_at TIMESTAMPTZ(3), disabled_at TIMESTAMPTZ(3), created_at TIMESTAMPTZ(3) NOT NULL DEFAULT now());
CREATE TABLE mfa_recovery_codes (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), mfa_method_id UUID NOT NULL REFERENCES mfa_methods(id) ON DELETE CASCADE, code_hash VARCHAR(128) NOT NULL, used_at TIMESTAMPTZ(3));
CREATE TABLE login_attempts (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), identifier_hash VARCHAR(128) NOT NULL, user_id UUID REFERENCES users(id) ON DELETE SET NULL, success BOOLEAN NOT NULL, ip_hash VARCHAR(128), user_agent TEXT, failure_reason VARCHAR(80), created_at TIMESTAMPTZ(3) NOT NULL DEFAULT now());
CREATE INDEX login_attempts_identifier_idx ON login_attempts(identifier_hash,created_at DESC);
CREATE TABLE user_devices (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE, device_hash VARCHAR(128) NOT NULL, label VARCHAR(100), first_seen_at TIMESTAMPTZ(3) NOT NULL DEFAULT now(), last_seen_at TIMESTAMPTZ(3) NOT NULL DEFAULT now(), revoked_at TIMESTAMPTZ(3), UNIQUE(user_id,device_hash));
CREATE TABLE user_preferences (user_id UUID PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE, theme VARCHAR(10) NOT NULL DEFAULT 'SYSTEM' CHECK(theme IN ('SYSTEM','LIGHT','DARK')), locale VARCHAR(10) NOT NULL DEFAULT 'ru' CHECK(locale IN ('ru','ky','en')), timezone VARCHAR(64) NOT NULL DEFAULT 'Asia/Bishkek', reduced_motion BOOLEAN NOT NULL DEFAULT false, settings_json JSONB NOT NULL DEFAULT '{}', updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT now());
CREATE TABLE student_profiles (user_id UUID PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE, birth_date DATE, guardian_name VARCHAR(200), guardian_contact VARCHAR(255), education_level VARCHAR(80), goals TEXT, onboarding_completed_at TIMESTAMPTZ(3));
CREATE TABLE mentor_profiles (user_id UUID PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE, bio TEXT, experience_years INTEGER CHECK(experience_years>=0), specialties TEXT[], is_public BOOLEAN NOT NULL DEFAULT false, booking_enabled BOOLEAN NOT NULL DEFAULT false);
CREATE TABLE staff_profiles (user_id UUID PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE, job_title VARCHAR(160), department VARCHAR(100), employee_number VARCHAR(80) UNIQUE, hired_at DATE, terminated_at DATE, is_public BOOLEAN NOT NULL DEFAULT false);

CREATE TABLE legal_documents (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), code VARCHAR(80) NOT NULL UNIQUE, type VARCHAR(30) NOT NULL, status "PublicationStatus" NOT NULL DEFAULT 'DRAFT', current_version_id UUID, created_at TIMESTAMPTZ(3) NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT now());
CREATE TABLE legal_document_versions (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), document_id UUID NOT NULL REFERENCES legal_documents(id) ON DELETE RESTRICT, version INTEGER NOT NULL, effective_from TIMESTAMPTZ(3), content_hash CHAR(64) NOT NULL, published_at TIMESTAMPTZ(3), created_by UUID REFERENCES users(id), created_at TIMESTAMPTZ(3) NOT NULL DEFAULT now(), UNIQUE(document_id,version));
ALTER TABLE legal_documents ADD CONSTRAINT legal_documents_current_version_fkey FOREIGN KEY(current_version_id) REFERENCES legal_document_versions(id);
CREATE TABLE legal_document_translations (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), version_id UUID NOT NULL REFERENCES legal_document_versions(id) ON DELETE CASCADE, locale VARCHAR(10) NOT NULL CHECK(locale IN ('ru','ky','en')), title TEXT NOT NULL, body_md TEXT NOT NULL, UNIQUE(version_id,locale));

CREATE TABLE media_assets (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), storage_provider VARCHAR(30) NOT NULL, bucket VARCHAR(100) NOT NULL, object_key TEXT NOT NULL, original_name TEXT NOT NULL, mime_type VARCHAR(150) NOT NULL, media_type VARCHAR(24) NOT NULL, size_bytes BIGINT NOT NULL CHECK(size_bytes>=0), checksum_sha256 CHAR(64), width INTEGER, height INTEGER, duration_seconds NUMERIC(12,3), status VARCHAR(20) NOT NULL DEFAULT 'UPLOADING', visibility VARCHAR(20) NOT NULL DEFAULT 'PRIVATE', uploaded_by UUID REFERENCES users(id), metadata JSONB NOT NULL DEFAULT '{}', created_at TIMESTAMPTZ(3) NOT NULL DEFAULT now(), deleted_at TIMESTAMPTZ(3), UNIQUE(storage_provider,bucket,object_key));
ALTER TABLE users ADD COLUMN avatar_media_id UUID REFERENCES media_assets(id) ON DELETE SET NULL;
CREATE TABLE media_variants (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), source_media_id UUID NOT NULL REFERENCES media_assets(id) ON DELETE CASCADE, kind VARCHAR(30) NOT NULL, media_id UUID NOT NULL REFERENCES media_assets(id) ON DELETE CASCADE, width INTEGER, height INTEGER, UNIQUE(source_media_id,kind));
CREATE TABLE upload_sessions (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE, purpose VARCHAR(40) NOT NULL, object_key TEXT NOT NULL UNIQUE, expected_size BIGINT CHECK(expected_size>=0), expires_at TIMESTAMPTZ(3) NOT NULL, completed_at TIMESTAMPTZ(3), created_at TIMESTAMPTZ(3) NOT NULL DEFAULT now());

CREATE TABLE branches (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), slug VARCHAR(160) NOT NULL UNIQUE, phone VARCHAR(30), email CITEXT, latitude NUMERIC(9,6) CHECK(latitude BETWEEN -90 AND 90), longitude NUMERIC(9,6) CHECK(longitude BETWEEN -180 AND 180), timezone VARCHAR(64) NOT NULL DEFAULT 'Asia/Bishkek', working_hours_json JSONB NOT NULL DEFAULT '{}', status "PublicationStatus" NOT NULL DEFAULT 'DRAFT', map_url TEXT, created_at TIMESTAMPTZ(3) NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT now());
CREATE TABLE branch_translations (branch_id UUID NOT NULL REFERENCES branches(id) ON DELETE CASCADE, locale VARCHAR(10) NOT NULL CHECK(locale IN ('ru','ky','en')), name TEXT NOT NULL, address TEXT NOT NULL, description TEXT, route_hint TEXT, PRIMARY KEY(branch_id,locale));
CREATE TABLE classrooms (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), branch_id UUID NOT NULL REFERENCES branches(id) ON DELETE RESTRICT, name VARCHAR(160) NOT NULL, capacity INTEGER NOT NULL CHECK(capacity>0), equipment_json JSONB NOT NULL DEFAULT '[]', accessible BOOLEAN NOT NULL DEFAULT false, status "PublicationStatus" NOT NULL DEFAULT 'DRAFT', created_at TIMESTAMPTZ(3) NOT NULL DEFAULT now(), UNIQUE(branch_id,name));
CREATE TABLE classroom_media (classroom_id UUID NOT NULL REFERENCES classrooms(id) ON DELETE CASCADE, media_id UUID NOT NULL REFERENCES media_assets(id) ON DELETE RESTRICT, sort_order INTEGER NOT NULL DEFAULT 0, PRIMARY KEY(classroom_id,media_id));

CREATE TABLE person_profiles (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id UUID REFERENCES users(id) ON DELETE SET NULL, slug VARCHAR(160) NOT NULL UNIQUE, kind VARCHAR(20) NOT NULL CHECK(kind IN ('FOUNDER','TEACHER','MENTOR','TEAM')), photo_media_id UUID REFERENCES media_assets(id) ON DELETE SET NULL, is_public BOOLEAN NOT NULL DEFAULT false, sort_order INTEGER NOT NULL DEFAULT 0, consent_expires_at TIMESTAMPTZ(3), published_at TIMESTAMPTZ(3), created_at TIMESTAMPTZ(3) NOT NULL DEFAULT now());
CREATE TABLE person_profile_translations (profile_id UUID NOT NULL REFERENCES person_profiles(id) ON DELETE CASCADE, locale VARCHAR(10) NOT NULL CHECK(locale IN ('ru','ky','en')), name TEXT NOT NULL, job_title TEXT, short_bio TEXT, bio TEXT, PRIMARY KEY(profile_id,locale));
CREATE TABLE person_social_links (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), profile_id UUID NOT NULL REFERENCES person_profiles(id) ON DELETE CASCADE, platform VARCHAR(30) NOT NULL, url TEXT NOT NULL, sort_order INTEGER NOT NULL DEFAULT 0);
CREATE TABLE companies (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), slug VARCHAR(160) NOT NULL UNIQUE, name VARCHAR(200) NOT NULL, website_url TEXT, logo_media_id UUID REFERENCES media_assets(id) ON DELETE SET NULL, is_verified BOOLEAN NOT NULL DEFAULT false);

CREATE TABLE course_categories (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), slug VARCHAR(160) NOT NULL UNIQUE, parent_id UUID REFERENCES course_categories(id) ON DELETE SET NULL, status "PublicationStatus" NOT NULL DEFAULT 'DRAFT', sort_order INTEGER NOT NULL DEFAULT 0);
CREATE TABLE course_category_translations (category_id UUID NOT NULL REFERENCES course_categories(id) ON DELETE CASCADE, locale VARCHAR(10) NOT NULL CHECK(locale IN ('ru','ky','en')), name TEXT NOT NULL, description TEXT, PRIMARY KEY(category_id,locale));
CREATE TABLE courses (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), slug VARCHAR(180) NOT NULL UNIQUE, category_id UUID REFERENCES course_categories(id) ON DELETE SET NULL, status "PublicationStatus" NOT NULL DEFAULT 'DRAFT', level "CourseLevel" NOT NULL DEFAULT 'BEGINNER', default_format "CourseFormat", cover_media_id UUID REFERENCES media_assets(id) ON DELETE SET NULL, duration_value INTEGER CHECK(duration_value>0), duration_unit VARCHAR(16), is_featured BOOLEAN NOT NULL DEFAULT false, published_version_id UUID, published_at TIMESTAMPTZ(3), archived_at TIMESTAMPTZ(3), created_at TIMESTAMPTZ(3) NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT now());
CREATE TABLE course_translations (course_id UUID NOT NULL REFERENCES courses(id) ON DELETE CASCADE, locale VARCHAR(10) NOT NULL CHECK(locale IN ('ru','ky','en')), title TEXT NOT NULL, short_description TEXT, description TEXT, learning_outcomes JSONB NOT NULL DEFAULT '[]', requirements JSONB NOT NULL DEFAULT '[]', seo_title TEXT, seo_description TEXT, PRIMARY KEY(course_id,locale));
CREATE TABLE course_versions (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), course_id UUID NOT NULL REFERENCES courses(id) ON DELETE RESTRICT, version INTEGER NOT NULL, status "PublicationStatus" NOT NULL DEFAULT 'DRAFT', change_summary TEXT, created_by UUID REFERENCES users(id), published_at TIMESTAMPTZ(3), created_at TIMESTAMPTZ(3) NOT NULL DEFAULT now(), UNIQUE(course_id,version));
ALTER TABLE courses ADD CONSTRAINT courses_published_version_fkey FOREIGN KEY(published_version_id) REFERENCES course_versions(id) ON DELETE SET NULL;
CREATE TABLE course_modules (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), course_version_id UUID NOT NULL REFERENCES course_versions(id) ON DELETE RESTRICT, position INTEGER NOT NULL CHECK(position>=0), is_required BOOLEAN NOT NULL DEFAULT true, unlock_rule_json JSONB NOT NULL DEFAULT '{}', UNIQUE(course_version_id,position));
CREATE TABLE course_module_translations (module_id UUID NOT NULL REFERENCES course_modules(id) ON DELETE CASCADE, locale VARCHAR(10) NOT NULL CHECK(locale IN ('ru','ky','en')), title TEXT NOT NULL, description TEXT, PRIMARY KEY(module_id,locale));
CREATE TABLE lessons (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), module_id UUID NOT NULL REFERENCES course_modules(id) ON DELETE RESTRICT, position INTEGER NOT NULL CHECK(position>=0), lesson_type VARCHAR(30) NOT NULL, estimated_minutes INTEGER CHECK(estimated_minutes>=0), is_required BOOLEAN NOT NULL DEFAULT true, available_from_offset_days INTEGER, status "PublicationStatus" NOT NULL DEFAULT 'DRAFT', created_at TIMESTAMPTZ(3) NOT NULL DEFAULT now(), UNIQUE(module_id,position));
CREATE TABLE lesson_translations (lesson_id UUID NOT NULL REFERENCES lessons(id) ON DELETE CASCADE, locale VARCHAR(10) NOT NULL CHECK(locale IN ('ru','ky','en')), title TEXT NOT NULL, summary TEXT, content_json JSONB NOT NULL DEFAULT '[]', PRIMARY KEY(lesson_id,locale));
CREATE TABLE lesson_materials (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), lesson_id UUID NOT NULL REFERENCES lessons(id) ON DELETE CASCADE, media_id UUID REFERENCES media_assets(id) ON DELETE RESTRICT, external_url TEXT, kind VARCHAR(30) NOT NULL, position INTEGER NOT NULL DEFAULT 0, is_downloadable BOOLEAN NOT NULL DEFAULT false, CHECK((media_id IS NOT NULL)::int+(external_url IS NOT NULL)::int=1));
CREATE TABLE course_staff (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), course_id UUID NOT NULL REFERENCES courses(id) ON DELETE RESTRICT, user_id UUID NOT NULL REFERENCES users(id) ON DELETE RESTRICT, staff_type VARCHAR(20) NOT NULL CHECK(staff_type IN ('TEACHER','MENTOR','AUTHOR')), starts_at TIMESTAMPTZ(3), ends_at TIMESTAMPTZ(3), is_public BOOLEAN NOT NULL DEFAULT false, CHECK(ends_at IS NULL OR starts_at IS NULL OR ends_at>starts_at));
CREATE TABLE course_prerequisites (course_id UUID NOT NULL REFERENCES courses(id) ON DELETE CASCADE, prerequisite_course_id UUID NOT NULL REFERENCES courses(id) ON DELETE RESTRICT, required BOOLEAN NOT NULL DEFAULT true, PRIMARY KEY(course_id,prerequisite_course_id), CHECK(course_id<>prerequisite_course_id));
CREATE TABLE course_tags (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), slug VARCHAR(100) NOT NULL UNIQUE);
CREATE TABLE course_tag_translations (tag_id UUID NOT NULL REFERENCES course_tags(id) ON DELETE CASCADE, locale VARCHAR(10) NOT NULL CHECK(locale IN ('ru','ky','en')), name TEXT NOT NULL, PRIMARY KEY(tag_id,locale));
CREATE TABLE course_tag_links (course_id UUID NOT NULL REFERENCES courses(id) ON DELETE CASCADE, tag_id UUID NOT NULL REFERENCES course_tags(id) ON DELETE CASCADE, PRIMARY KEY(course_id,tag_id));

CREATE TABLE tariffs (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), course_id UUID NOT NULL REFERENCES courses(id) ON DELETE RESTRICT, code VARCHAR(60) NOT NULL, status "PublicationStatus" NOT NULL DEFAULT 'DRAFT', access_days INTEGER CHECK(access_days>0), includes_mentor BOOLEAN NOT NULL DEFAULT false, includes_recordings BOOLEAN NOT NULL DEFAULT false, features_json JSONB NOT NULL DEFAULT '[]', created_at TIMESTAMPTZ(3) NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT now(), UNIQUE(course_id,code));
CREATE TABLE tariff_translations (tariff_id UUID NOT NULL REFERENCES tariffs(id) ON DELETE CASCADE, locale VARCHAR(10) NOT NULL CHECK(locale IN ('ru','ky','en')), name TEXT NOT NULL, description TEXT, PRIMARY KEY(tariff_id,locale));
CREATE TABLE prices (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), tariff_id UUID NOT NULL REFERENCES tariffs(id) ON DELETE RESTRICT, currency CHAR(3) NOT NULL CHECK(currency ~ '^[A-Z]{3}$'), amount_minor BIGINT NOT NULL CHECK(amount_minor>=0), valid_from TIMESTAMPTZ(3) NOT NULL, valid_until TIMESTAMPTZ(3), is_active BOOLEAN NOT NULL DEFAULT true, CHECK(valid_until IS NULL OR valid_until>valid_from));
CREATE TABLE discounts (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), name VARCHAR(160) NOT NULL, type VARCHAR(10) NOT NULL CHECK(type IN ('PERCENT','FIXED')), value NUMERIC(12,2) NOT NULL CHECK(value>=0), currency CHAR(3), starts_at TIMESTAMPTZ(3), ends_at TIMESTAMPTZ(3), usage_limit INTEGER, per_user_limit INTEGER, status "PublicationStatus" NOT NULL DEFAULT 'DRAFT', CHECK(type<>'PERCENT' OR value<=100), CHECK(ends_at IS NULL OR starts_at IS NULL OR ends_at>starts_at));
CREATE TABLE discount_targets (discount_id UUID NOT NULL REFERENCES discounts(id) ON DELETE CASCADE, course_id UUID REFERENCES courses(id) ON DELETE CASCADE, tariff_id UUID REFERENCES tariffs(id) ON DELETE CASCADE, CHECK(course_id IS NOT NULL OR tariff_id IS NOT NULL));
CREATE TABLE promo_codes (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), discount_id UUID NOT NULL REFERENCES discounts(id) ON DELETE RESTRICT, code VARCHAR(80) NOT NULL UNIQUE, starts_at TIMESTAMPTZ(3), ends_at TIMESTAMPTZ(3), usage_limit INTEGER, per_user_limit INTEGER, status "PublicationStatus" NOT NULL DEFAULT 'DRAFT');

CREATE TABLE "groups" (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), course_id UUID NOT NULL REFERENCES courses(id) ON DELETE RESTRICT, course_version_id UUID NOT NULL REFERENCES course_versions(id) ON DELETE RESTRICT, branch_id UUID REFERENCES branches(id) ON DELETE SET NULL, classroom_id UUID REFERENCES classrooms(id) ON DELETE SET NULL, code VARCHAR(100) NOT NULL UNIQUE, status "GroupStatus" NOT NULL DEFAULT 'DRAFT', format "CourseFormat" NOT NULL, capacity INTEGER NOT NULL CHECK(capacity>0), starts_on DATE NOT NULL, ends_on DATE, enrollment_opens_at TIMESTAMPTZ(3), enrollment_closes_at TIMESTAMPTZ(3), timezone VARCHAR(64) NOT NULL DEFAULT 'Asia/Bishkek', created_at TIMESTAMPTZ(3) NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT now(), CHECK(ends_on IS NULL OR ends_on>=starts_on));
CREATE TABLE group_staff (group_id UUID NOT NULL REFERENCES "groups"(id) ON DELETE CASCADE, user_id UUID NOT NULL REFERENCES users(id) ON DELETE RESTRICT, role VARCHAR(20) NOT NULL CHECK(role IN ('TEACHER','MENTOR','ASSISTANT')), starts_at TIMESTAMPTZ(3), ends_at TIMESTAMPTZ(3), PRIMARY KEY(group_id,user_id,role));
CREATE TABLE group_schedule_rules (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), group_id UUID NOT NULL REFERENCES "groups"(id) ON DELETE CASCADE, weekday SMALLINT NOT NULL CHECK(weekday BETWEEN 1 AND 7), starts_at TIME NOT NULL, ends_at TIME NOT NULL, valid_from DATE NOT NULL, valid_until DATE, classroom_id UUID REFERENCES classrooms(id), meeting_url TEXT, CHECK(ends_at>starts_at));
CREATE TABLE class_sessions (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), group_id UUID NOT NULL REFERENCES "groups"(id) ON DELETE RESTRICT, lesson_id UUID REFERENCES lessons(id) ON DELETE SET NULL, classroom_id UUID REFERENCES classrooms(id) ON DELETE SET NULL, starts_at TIMESTAMPTZ(3) NOT NULL, ends_at TIMESTAMPTZ(3) NOT NULL, status VARCHAR(20) NOT NULL DEFAULT 'SCHEDULED', meeting_url TEXT, recording_media_id UUID REFERENCES media_assets(id), notes TEXT, CHECK(ends_at>starts_at));
CREATE INDEX groups_catalog_idx ON "groups"(course_id,status,starts_on);
CREATE INDEX class_sessions_upcoming_idx ON class_sessions(group_id,starts_at) WHERE status<>'CANCELLED';

COMMIT;
